version: '2'
services:
  veranet:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - veranet_ControlSockEnabled=0
      - veranet_ControlPortEnabled=1
    volumes:
      - ./bin:/root/veranet/bin
      - ./lib:/root/veranet/lib
      - ./test:/root/veranet/test
      - ./index.js:/root/veranet/index.js
      - ./node_modules:/root/veranet/node_modules
      - ./package.json:/root/veranet/package.json
    ports:
      - "8372:8372"
      - "127.0.0.1:8373:8373"
